namespace : sasoperator
resources :
  - sas-bases/base
  - sas-bases/overlays/cert-manager-issuer
  - sas-bases/overlays/network/networking.k8s.io  
  - sas-bases/overlays/cas-server
  - sas-bases/overlays/crunchydata/postgres-operator
  - sas-bases/overlays/postgres/platform-postgres
#if your deployment contains SAS Viya Programming, comment out the next line
  - sas-bases/overlays/internal-elasticsearch
  - sas-bases/overlays/update-checker
  - sas-bases/overlays/cas-server/auto-resources 
configurations:
  - sas-bases/overlays/required/kustomizeconfig.yaml
transformers:
     # If your deployment does not support privileged containers or if your deployment
     # contains SAS Viya Programming, comment out the next line
  - sas-bases/overlays/cert-manager-provided-ingress-certificate/ingress-annotation-transformer.yaml
  - sas-bases/overlays/internal-elasticsearch/sysctl-transformer.yaml
  - sas-bases/overlays/required/transformers.yaml
  - sas-bases/overlays/cas-server/auto-resources/remove-resources.yaml  
     # If your deployment contains SAS Viya Programming, comment out the next line
  - sas-bases/overlays/internal-elasticsearch/internal-elasticsearch-transformer.yaml
     # Mount information
     # - site-config/{{ DIRECTORY-PATH }}/cas-add-host-mount.yaml
components: 
  - sas-bases/components/crunchydata/internal-platform-postgres 
  - sas-bases/components/security/core/base/full-stack-tls 
  - sas-bases/components/security/network/networking.k8s.io/ingress/nginx.ingress.kubernetes.io/full-stack-tls 
patches:
- path: site-config/storageclass.yaml 
  target:
    kind: PersistentVolumeClaim
    annotationSelector: sas.com/component-name in (sas-backup-job,sas-data-quality-services,sas-commonfiles,sas-cas-operator,sas-pyconfig)
               # License information
               # secretGenerator:
               # - name: sas-license
               #   type: sas.com/license
               #   behavior: merge
               #   files:
               #   - SAS_LICENSE=license.jwt
generators:
  - site-config/security/customer-provided-ingress-certificate.yaml 
  - site-config/security/customer-provided-ca-certificates.yaml
  - site-config/security/customer-provided-merge-sas-certframe-configmap.yaml # merges customer-provided configuration settings into the sas-certframe-user-config configmap
configMapGenerator:
- name : ingress-input
  behavior: merge
  literals:
  - INGRESS_HOST=sas-biware.com
- name : sas-shared-config
  behavior : merge    
  literals:
  - SAS_SERVICES_URL=https://sas-biware.com:443
                             # - SAS_ URL_EXTERNAL_VIYA={{ EXTERNAL-PROXY-URL }} 


  





