apiVersion: orchestration.sas.com/v2beta5
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-pyconfig
    sas.com/component-version: 1.8.14-20230301.1677677702866
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: sas-pyconfig
  name: deploy-assess-pyconfig-execute
spec:
  args:
  - name: namespace
  steps:
  - args:
    - annotate
    - --namespace
    - $namespace
    - configmap
    - sas-deploy-lifecycle-operation-variables
    - sas.com/sas-pyconfig-update=true
    - --overwrite
    cmd: kubectl
